#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Users\Public\Documents\Robotics\Includes\JoystickDriver.h"

void drive()
{
	float y = joyY(1,0);
	float x = joyX(1,0);

	float aPower = 0;
	float bPower = 0;

	aPower = (x / 2) + (y / 2);
	bPower = (x / -2) + (y / 2);

	aPower = aPower * (100/128);
	bPower = bPower * (100/128);

	motor[motorD] = bPower;
	motor[motorF] = bPower;
	motor[motorE] = aPower;
	motor[motorG] = aPower;

	nxtDisplayTextLine(2,"aPower: %s",aPower);
	nxtDisplayTextLine(4,"bPower: %s",bPower);
}

task main()
{
	getJoystickSettings(joystick);
	while(true)
	{
		if (getJoystickSettings(joystick) == true)
		{
			drive();
		}
	}
}
