#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/* A = RightFront
B = RightBack
C = LeftBack
D = LeftFront */

const int GearRatio = 1; //ratio
const int WheelDiameter = 3.8; //in inches
const float InchesToEncoders = GearRatio * WheelDiameter * PI / 1440; //inches to encoder counts (duh)
const float root2over2 = sqrt(2) / 2;


void MecaMove(int x, int y, int speed)
{
	int AC_dif = y + x; //vector parts
	int BD_dif = y - x;

	int AC_speed = 0;
	int BD_speed = 0;

	int AC_distance = AC_dif * root2over2 * InchesToEncoders; //create distance in encoders
	int BD_distance = BD_dif * root2over2 * InchesToEncoders;


	// prepare motor speeds
	if(AC_distance >= BD_distance) //if the AC traslation will be greater than it will be faster, and the BD will be slower
	{
		AC_speed = speed;
		BD_speed = speed * BD_distance / AC_distance;
	}
	else  // ^^ vica versa
	{
		AC_speed = speed * AC_distance / BD_distance;
		BD_speed = speed;
	}


	// set encoders to 0
	nMotorEncoder[LeftFront] = 0;
	nMotorEncoder[LeftBack] = 0;
	nMotorEncoder[RightFront] = 0;
	nMotorEncoder[RightBack] = 0;

	// while all the wheels are reaching their target MN_distance
	while ((nMotorEncoder[LeftBack] < AC_distance && nMotorEncoder[RightFront] <AC_distance) && (nMotorEncoder[LeftFront] < BD_distance && nMotorEncoder[RightBack] < BD_distance))
	{
		motor[LeftBack] = AC_speed;
		motor[RightFront] = AC_speed;
		motor[LeftFront] = BD_speed;
		motor[RightBack] = BD_speed;
	}

}

task main()
{
	MecaMove(x,y,speed); //(x,y) coordinates then speed of faster motor
}
