#pragma config(Motor,  motorA,          Left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNXT, PIDControl, encoder)
#pragma config(Sensor, S1,     HTIRS2,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Includes\rdpartyrobotcdr-3.0b1\drivers\hitechnic-irseeker-v2.h"

task main()
{
	int _dirAC = 0;
	const int head = 5;
	int diff = 0;

	while(_dirAC < 100)
	{
		_dirAC = HTIRS2readACDir(HTIRS2);

		if (_dirAC != 0)
		{
			diff = _dirAC - head;
		}
		else
		{
			diff = 0;
		}

		motor[Left] = 50 + diff*25;
		motor[Right] = 50 - diff*25;

		wait1Msec(10);
	}
}
