#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int leftpower = 0;
int rightpower = 0;

task main()
{
	getJoystickSettings(joystick);

	while(true)  //infinite loop
	{
		rightpower = joystick.joy1_y2;		//read joystick y values (both sticks)
		leftpower = joystick.joy1_y1;

		if(abs(rightpower) < 9)			//deadband with threshold of 9

			{
					rightpower = 0;
			}

		if(abs(leftpower) < 9)			//deadband with threshold of 9

			{
				leftpower = 0;
			}

		motor[LeftDrive] = -leftpower;		//TURN LEFTDRIVE AT leftpower
		motor[RightDrive] = rightpower;		//TURN RIGHTDRIVE AT rightpower
	}

}
